development:
  adapter: postgresql
  encoding: unicode
  database: AluDir_development
  pool: 5
  username: aludir
  password: alumniRulez

test:
  adapter: postgresql
  encoding: unicode
  database: AluDir_test
  pool: 5
  username: aludir
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: AluDir_production
  pool: 5
  username: aludir
  password:
